### ISSUE TITLE
Enable fully local development setup

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-cloudserver#33]
Currently an Azure account and the network are required to run the project locally. Ideally we'd create an alternative setup that can be run entirely locally.

- [x] Blob storage -> [libcloud](https://github.com/apache/libcloud) (see https://github.com/ascoderu/opwen-cloudserver/issues/46)
- [x] Table storage -> [libcloud](https://github.com/apache/libcloud) (see https://github.com/ascoderu/opwen-cloudserver/issues/54)
- [x] ServiceBus queue -> [celery](https://github.com/celery/celery) (see https://github.com/ascoderu/opwen-cloudserver/issues/45)
- [x] Sendgrid emails -> logging

**Comment by c-w** [comment]
Now that the base pieces of the local development setup are merged, the remaining piece is to wire up the local modes for docker-compose.
